//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
    using System;
    
    
                // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WE1M1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WE1M1() {
        }
        
                                [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.WE1M1", typeof(WE1M1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
                                        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
                                internal static System.Drawing.Bitmap _1dolar {
            get {
                object obj = ResourceManager.GetObject("_1dolar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
                                internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
                                internal static System.Drawing.Bitmap bolsonaro {
            get {
                object obj = ResourceManager.GetObject("bolsonaro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
                                internal static System.Drawing.Bitmap lula {
            get {
                object obj = ResourceManager.GetObject("lula", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
                                internal static System.Drawing.Bitmap MapGrid {
            get {
                object obj = ResourceManager.GetObject("MapGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
                                internal static System.Drawing.Bitmap pt {
            get {
                object obj = ResourceManager.GetObject("pt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
                                internal static System.Drawing.Bitmap WolfTextures {
            get {
                object obj = ResourceManager.GetObject("WolfTextures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
